# Generated by Django 4.2.3 on 2023-08-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="feeding date")),
                (
                    "readings",
                    models.CharField(
                        choices=[
                            ("M", "Morning"),
                            ("A", "Afternoon"),
                            ("E", "Evening"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "comic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.comic"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
